language: java

script: mvn clean install -DskipTests=false

jdk:
  - oraclejdk8

notifications:
  recipients:
    - andreswinck@gmail.com
  email:
    on_success: change
    on_failure: change

cache:
  directories:
    - $HOME/.m2
